//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoRobo.ClientLib.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoRobo.ClientLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap account {
            get {
                object obj = ResourceManager.GetObject("account", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 if (!window.XMLHttpRequest) {
        ///
        ///    window.XMLHttpRequest = function () {
        ///        return new ActiveXObject(&apos;Microsoft.XMLHTTP&apos;);
        ///    }
        ///}
        ///function AjaxMonitorForWatiN() {
        ///    this.count = 0;
        ///
        ///    this.callback = function () {
        ///        this.count--;
        ///        if (this.count &gt; 0) return;
        ///        var c = typeof window.external.Call;
        ///        if (c == &apos;undefined&apos;) return;
        ///        window.external.Call(&apos;MatchHandler&apos;, { event: &apos;ajaxComplete&apos; });
        ///    }
        ///}
        ///var ajaxWatin = new AjaxMonitorForWatiN();
        ///var x [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ajaxMoniter {
            get {
                return ResourceManager.GetString("ajaxMoniter", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap at {
            get {
                object obj = ResourceManager.GetObject("at", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap configButton {
            get {
                object obj = ResourceManager.GetObject("configButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cutInfo {
            get {
                object obj = ResourceManager.GetObject("cutInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap debugBtn {
            get {
                object obj = ResourceManager.GetObject("debugBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap docRefresh {
            get {
                object obj = ResourceManager.GetObject("docRefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 if (typeof __domready == &apos;undefined&apos;) {
        ///    __domready = &apos;&apos;;
        ///
        ///    function bindReady(handler) {
        ///
        ///        var called = false
        ///
        ///        function ready() {
        ///            if (called) return
        ///            called = true
        ///            handler()
        ///        }
        ///
        ///        if (document.addEventListener) { // native event
        ///            document.addEventListener(&quot;DOMContentLoaded&quot;, ready, false)
        ///        } 
        ///       if (document.attachEvent) {  // IE
        ///
        ///            try {
        ///                var isFrame = window.frameElement  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string domReady {
            get {
                return ResourceManager.GetString("domReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /**
        ///    * jQuery.deserialize plugin
        ///    * Fills elements in selected containers with data extracted from URLencoded string
        ///    * @param data URLencoded data
        ///    * @param clearForm if true form will be cleared prior to deserialization
        ///    */
        ///    $jq.fn.deserialize = function (data, clearForm) {
        ///        this.each(function () {
        ///            deserialize(this, data, !!clearForm);
        ///        });
        ///    };
        ///
        ///    /**
        ///    * Fills specified form with data extracted from string
        ///    * @param element form to fill        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string formDeserialize {
            get {
                return ResourceManager.GetString("formDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function () {
        ///        var count = 0, frames;
        ///        frames = document.getElementsByTagName(&quot;iframe&quot;);
        ///
        ///        document.attachEvent(&quot;onreadystatechange&quot;, function () {
        ///            if (document.readyState === &quot;complete&quot;) {
        ///                count++;
        ///                statusCheck();
        ///            }
        ///        });
        ///        if (document.readyState === &quot;complete&quot;) {
        ///            count++;
        ///            statusCheck();
        ///        }
        ///
        ///        for (var i = 0; i &lt; frames.length; ++i) {
        ///            var iframe = frames [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string iframeMoniter {
            get {
                return ResourceManager.GetString("iframeMoniter", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap mail {
            get {
                object obj = ResourceManager.GetObject("mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap msgButton {
            get {
                object obj = ResourceManager.GetObject("msgButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav {
            get {
                object obj = ResourceManager.GetObject("nav", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap register_email {
            get {
                object obj = ResourceManager.GetObject("register_email", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap selection {
            get {
                object obj = ResourceManager.GetObject("selection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap taskButton {
            get {
                object obj = ResourceManager.GetObject("taskButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
