//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoRobo.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoRobo.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1369654724_wizard {
            get {
                object obj = ResourceManager.GetObject("1369654724_wizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Collection is read-only 的本地化字符串。
        /// </summary>
        internal static string BaseComponentCollection_CollectionIsReadonly {
            get {
                return ResourceManager.GetString("BaseComponentCollection_CollectionIsReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collection does not support searching by equality. 的本地化字符串。
        /// </summary>
        internal static string BaseComponentCollection_DoesNotSupportSearchingByEquality {
            get {
                return ResourceManager.GetString("BaseComponentCollection_DoesNotSupportSearchingByEquality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found {0}{1} 的本地化字符串。
        /// </summary>
        internal static string CacheCookieFound {
            get {
                return ResourceManager.GetString("CacheCookieFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not do multi-file drop! 的本地化字符串。
        /// </summary>
        internal static string CanNotDoMultiFileDrop {
            get {
                return ResourceManager.GetString("CanNotDoMultiFileDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Language 的本地化字符串。
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code Language 的本地化字符串。
        /// </summary>
        internal static string CodeLanguage {
            get {
                return ResourceManager.GetString("CodeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compile Path ({0}) could not be created.  Please modify it in the Settings. 的本地化字符串。
        /// </summary>
        internal static string CompilePathCouldNotBeCreated {
            get {
                return ResourceManager.GetString("CompilePathCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compiler Error: {0} 的本地化字符串。
        /// </summary>
        internal static string CompilerError {
            get {
                return ResourceManager.GetString("CompilerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compiler Errors 的本地化字符串。
        /// </summary>
        internal static string CompilerErrors {
            get {
                return ResourceManager.GetString("CompilerErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compile successful, but can&apos;t find {0} 的本地化字符串。
        /// </summary>
        internal static string CompileSuccessfulButCantFind {
            get {
                return ResourceManager.GetString("CompileSuccessfulButCantFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compiling completed with no errors 的本地化字符串。
        /// </summary>
        internal static string CompilingCompletedWithNoErrors {
            get {
                return ResourceManager.GetString("CompilingCompletedWithNoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compiling completed with no errors, running now 的本地化字符串。
        /// </summary>
        internal static string CompilingCompletedWithNoErrorsRunningNow {
            get {
                return ResourceManager.GetString("CompilingCompletedWithNoErrorsRunningNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compiling Script... 的本地化字符串。
        /// </summary>
        internal static string CompilingScript {
            get {
                return ResourceManager.GetString("CompilingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirmation 的本地化字符串。
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirmation Requested 的本地化字符串。
        /// </summary>
        internal static string ConfirmationRequested {
            get {
                return ResourceManager.GetString("ConfirmationRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirmation Required 的本地化字符串。
        /// </summary>
        internal static string ConfirmationRequired {
            get {
                return ResourceManager.GetString("ConfirmationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The control has already been initialized. 的本地化字符串。
        /// </summary>
        internal static string Control_HasAlreadyBeenInitialized {
            get {
                return ResourceManager.GetString("Control_HasAlreadyBeenInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete all {0} items? 的本地化字符串。
        /// </summary>
        internal static string DeleteAllItems {
            get {
                return ResourceManager.GetString("DeleteAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete {0} checked items? 的本地化字符串。
        /// </summary>
        internal static string DeleteCheckedItems {
            get {
                return ResourceManager.GetString("DeleteCheckedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleted {0} Cache Entries 的本地化字符串。
        /// </summary>
        internal static string DeletedCacheEntries {
            get {
                return ResourceManager.GetString("DeletedCacheEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleted {0} Cache Entries from
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string DeletedCacheEntriesFromPath {
            get {
                return ResourceManager.GetString("DeletedCacheEntriesFromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleted {0} Cookies 的本地化字符串。
        /// </summary>
        internal static string DeletedCookies {
            get {
                return ResourceManager.GetString("DeletedCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleted {0} Cookies from {1} 的本地化字符串。
        /// </summary>
        internal static string DeletedCookiesFromPath {
            get {
                return ResourceManager.GetString("DeletedCookiesFromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete {0} selected items? 的本地化字符串。
        /// </summary>
        internal static string DeleteSelectedItems {
            get {
                return ResourceManager.GetString("DeleteSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DOM Error Highlighting 的本地化字符串。
        /// </summary>
        internal static string DOMErrorHighlighting {
            get {
                return ResourceManager.GetString("DOMErrorHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have an unsaved script, and loading will erase it.  Erase and continue loading? 的本地化字符串。
        /// </summary>
        internal static string EraseAndContinueLoading {
            get {
                return ResourceManager.GetString("EraseAndContinueLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {4} [{0}] at Line {1} Column {2}: {3} 的本地化字符串。
        /// </summary>
        internal static string ErrorLineListing {
            get {
                return ResourceManager.GetString("ErrorLineListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There were errors compiling your script:
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string ErrorsCompilingYourScript {
            get {
                return ResourceManager.GetString("ErrorsCompilingYourScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File {0} does not exist 的本地化字符串。
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Error 的本地化字符串。
        /// </summary>
        internal static string FileError {
            get {
                return ResourceManager.GetString("FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find {0} 的本地化字符串。
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find in Page 的本地化字符串。
        /// </summary>
        internal static string FindInPage {
            get {
                return ResourceManager.GetString("FindInPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found {0} matches 的本地化字符串。
        /// </summary>
        internal static string FoundMatches {
            get {
                return ResourceManager.GetString("FoundMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function Explorer - {0} 的本地化字符串。
        /// </summary>
        internal static string FunctionExplorer {
            get {
                return ResourceManager.GetString("FunctionExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Password 的本地化字符串。
        /// </summary>
        internal static string HidePassword {
            get {
                return ResourceManager.GetString("HidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Closing IE instance 的本地化字符串。
        /// </summary>
        internal static string IE_Dispose {
            get {
                return ResourceManager.GetString("IE_Dispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function (jQuery, undefined) {
        ///
        ///        var push = Array.prototype.push,
        ///    rcheck = /^(?:radio|checkbox)$/i,
        ///    rplus = /\+/g,
        ///    rselect = /^(?:option|select-one|select-multiple)$/i,
        ///    rvalue = /^(?:button|color|date|datetime|datetime-local|email|hidden|month|number|password|range|reset|search|submit|tel|text|textarea|time|url|week)$/i;
        ///
        ///        function getElements(elements) {
        ///            return elements.map(function () {
        ///                return this.elements ? jQuery.makeArray(this.elemen [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string jqDeserialize {
            get {
                return ResourceManager.GetString("jqDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /*! jQuery v1.8.2 jquery.com | jquery.org/license */
        ///(function(a,b){function G(a){var b=F[a]={};return p.each(a.split(s),function(a,c){b[c]=!0}),b}function J(a,c,d){if(d===b&amp;&amp;a.nodeType===1){var e=&quot;data-&quot;+c.replace(I,&quot;-$1&quot;).toLowerCase();d=a.getAttribute(e);if(typeof d==&quot;string&quot;){try{d=d===&quot;true&quot;?!0:d===&quot;false&quot;?!1:d===&quot;null&quot;?null:+d+&quot;&quot;===d?+d:H.test(d)?p.parseJSON(d):d}catch(f){}p.data(a,c,d)}else d=b}return d}function K(a){var b;for(b in a){if(b===&quot;data&quot;&amp;&amp;p.isEmptyObject(a[b]))continue;if(b!==&quot;toJSON&quot;)ret [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Jquery {
            get {
                return ResourceManager.GetString("Jquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 $jq.fn.isChildOf = function (b) {            
        ///    if ($jq(this).is(b)) return false;
        ///    return (this.closest(b).length &gt; 0);
        ///} 
        /////如果parentCssPath不为空，则获取先对路径，如果当前元素不是parentCssPath的子元素，报告异常,如果是
        /////返回相对路径
        ///$jq.fn.getCssPath = function (context) {
        ///
        ///    if (this.length != 1) throw &apos;Requires one element.&apos;;
        ///    var path, node = this;
        ///		if(typeof context == &apos;undefined&apos;){
        ///			context = &apos;&apos;;
        ///		}
        ///    while (node.length) {
        ///        var realNode = node[0];
        ///        if(context != &apos;&apos;){
        ///        	if (!$jq(realNod [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string JquerySelector {
            get {
                return ResourceManager.GetString("JquerySelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Known Bug 的本地化字符串。
        /// </summary>
        internal static string KnownBug {
            get {
                return ResourceManager.GetString("KnownBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must restart to change languges.  Do that now? 的本地化字符串。
        /// </summary>
        internal static string LanguageChange {
            get {
                return ResourceManager.GetString("LanguageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List of resources: 的本地化字符串。
        /// </summary>
        internal static string ListOfResources {
            get {
                return ResourceManager.GetString("ListOfResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded code is in a different code language. 的本地化字符串。
        /// </summary>
        internal static string LoadedCodeInDifferentLang {
            get {
                return ResourceManager.GetString("LoadedCodeInDifferentLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message sent successfully 的本地化字符串。
        /// </summary>
        internal static string MessageSentSuccessfully {
            get {
                return ResourceManager.GetString("MessageSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Necessary code files could not be found. 的本地化字符串。
        /// </summary>
        internal static string NecessaryCodeFilesCouldNotBeFound {
            get {
                return ResourceManager.GetString("NecessaryCodeFilesCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Default 的本地化字符串。
        /// </summary>
        internal static string NoDefault {
            get {
                return ResourceManager.GetString("NoDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No default template has been selected.  Please select from the list. 的本地化字符串。
        /// </summary>
        internal static string NoDefaultTemplateSelected {
            get {
                return ResourceManager.GetString("NoDefaultTemplateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Items Found 的本地化字符串。
        /// </summary>
        internal static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No more matches found for {0} 的本地化字符串。
        /// </summary>
        internal static string NoMoreMatchesFound {
            get {
                return ResourceManager.GetString("NoMoreMatchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No tests to compile 的本地化字符串。
        /// </summary>
        internal static string NoTestsToCompile {
            get {
                return ResourceManager.GetString("NoTestsToCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No tests to run 的本地化字符串。
        /// </summary>
        internal static string NoTestsToRun {
            get {
                return ResourceManager.GetString("NoTestsToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The page type is expected to be a subclass of Page. 的本地化字符串。
        /// </summary>
        internal static string PageMetadata_PageTypeIsExpectedToBeASubclassOfPage {
            get {
                return ResourceManager.GetString("PageMetadata_PageTypeIsExpectedToBeASubclassOfPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://watintestrecord.sourceforge.net/TestRecorderInterfaces.html 的本地化字符串。
        /// </summary>
        internal static string RecorderHelpURL {
            get {
                return ResourceManager.GetString("RecorderHelpURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A match operation has been aborted because it appeared to be re-entrant.  The exception occurred in an instance of &apos;{0}&apos; with constraint: {1}. 的本地化字符串。
        /// </summary>
        internal static string ReEntryException_MessageFormat {
            get {
                return ResourceManager.GetString("ReEntryException_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove all cache entries? 的本地化字符串。
        /// </summary>
        internal static string RemoveAllCacheEntries {
            get {
                return ResourceManager.GetString("RemoveAllCacheEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proceed to remove all cookies? 的本地化字符串。
        /// </summary>
        internal static string RemoveAllCookies {
            get {
                return ResourceManager.GetString("RemoveAllCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proceed to remove all History entries? 的本地化字符串。
        /// </summary>
        internal static string RemoveAllHistory {
            get {
                return ResourceManager.GetString("RemoveAllHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove cache entries from {0} ? 的本地化字符串。
        /// </summary>
        internal static string RemoveCacheEntriesFromPath {
            get {
                return ResourceManager.GetString("RemoveCacheEntriesFromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove cookies from {0} ? 的本地化字符串。
        /// </summary>
        internal static string RemoveCookiesFromPath {
            get {
                return ResourceManager.GetString("RemoveCookiesFromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Error - Not Saved 的本地化字符串。
        /// </summary>
        internal static string SaveErrorNotSaved {
            get {
                return ResourceManager.GetString("SaveErrorNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.google.com/search?q={0}&amp;btnG=Google+Search&amp;meta= 的本地化字符串。
        /// </summary>
        internal static string SearchURL {
            get {
                return ResourceManager.GetString("SearchURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 $jq(&apos;select&apos;).change(function () {
        ///            window.external.SelectOnChange(this);
        ///        }); 的本地化字符串。
        /// </summary>
        internal static string SelectChange {
            get {
                return ResourceManager.GetString("SelectChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] Send cancelled 的本地化字符串。
        /// </summary>
        internal static string SendCanceled {
            get {
                return ResourceManager.GetString("SendCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Mail Error 的本地化字符串。
        /// </summary>
        internal static string SendMailError {
            get {
                return ResourceManager.GetString("SendMailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An HTML Dialog cannot be tracked by this application.
        ///If you know someone at Microsoft who can change this, we&apos;d love to support it. (MSDN KB251128)
        ///
        ///Continue opening the page? 的本地化字符串。
        /// </summary>
        internal static string showDialogBug {
            get {
                return ResourceManager.GetString("showDialogBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Password 的本地化字符串。
        /// </summary>
        internal static string ShowPassword {
            get {
                return ResourceManager.GetString("ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function(){var a=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|[&apos;&quot;][^&apos;&quot;]*[&apos;&quot;]|[^\[\]&apos;&quot;]+)+\]|\\.|[^ &gt;+~,(\[\\]+)+|[&gt;+~])(\s*,\s*)?((?:.|\r|\n)*)/g,b=0,c=Object.prototype.toString,d=!1,e=!0;[0,0].sort(function(){e=!1;return 0});var f=function(b,d,e,i){e=e||[],d=d||document;var j=d;if(d.nodeType!==1&amp;&amp;d.nodeType!==9)return[];if(!b||typeof b!==&quot;string&quot;)return e;var l,m,n,o,p,r,s,t,u=!0,v=f.isXML(d),w=[],x=b;do{a.exec(&quot;&quot;),l=a.exec(x);if(l){x=l[3],w.push(l[1]);if(l[2]){o=l[3];break}}}while(l);if(w.length&gt;1&amp;&amp; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string sizzle {
            get {
                return ResourceManager.GetString("sizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some items cannot be found, preventing compilation.  Please find these resources: 的本地化字符串。
        /// </summary>
        internal static string SomeItemsCannotBeFound {
            get {
                return ResourceManager.GetString("SomeItemsCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target template is set not to compile 的本地化字符串。
        /// </summary>
        internal static string TargetTemplateIsSetNotToCompile {
            get {
                return ResourceManager.GetString("TargetTemplateIsSetNotToCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Source - {0} 的本地化字符串。
        /// </summary>
        internal static string Test_Source_Tab {
            get {
                return ResourceManager.GetString("Test_Source_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Name 的本地化字符串。
        /// </summary>
        internal static string TestName {
            get {
                return ResourceManager.GetString("TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test name can contain only A-Z and 0-9 的本地化字符串。
        /// </summary>
        internal static string TestNameCanContainOnlyAZAnd09 {
            get {
                return ResourceManager.GetString("TestNameCanContainOnlyAZAnd09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Recorder Code (*.trc)|*.trc 的本地化字符串。
        /// </summary>
        internal static string TestRecorderCodeType {
            get {
                return ResourceManager.GetString("TestRecorderCodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tests must have a name. 的本地化字符串。
        /// </summary>
        internal static string TestsMustHaveAName {
            get {
                return ResourceManager.GetString("TestsMustHaveAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // Unknown Item  的本地化字符串。
        /// </summary>
        internal static string UnknownItem {
            get {
                return ResourceManager.GetString("UnknownItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your script is unsaved.  Continue closing? 的本地化字符串。
        /// </summary>
        internal static string UnsavedScript {
            get {
                return ResourceManager.GetString("UnsavedScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsaved Script 的本地化字符串。
        /// </summary>
        internal static string UnsavedScript_title {
            get {
                return ResourceManager.GetString("UnsavedScript_title", resourceCulture);
            }
        }
    }
}
